service: python-aws-lambda-serverless
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  versionFunctions: false
  memorySize: 128
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: echo/hello
          method: get
